# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Fri, 17 Jun 2016 04:48:19 +0000
*	@ALL	0
*	@user	8
playground:playground	@user	0
