# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Fri, 12 May 2017 04:18:01 +0000
*               @ALL          0
*               @user         8
