<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: smpark
 * Date: Thu, 06 Apr 2017 14:13:35 +0830
 */

$conf['title'] = '찡 위키';
$conf['license'] = '';
$conf['plugin']['indexmenu']['aclcache'] = 'none';
$conf['plugin']['syntaxhighlighter4']['theme'] = 'theme-eclipse.css';
$conf['plugin']['syntaxhighlightjs']['theme'] = 'github';
$conf['tpl']['white']['numberedHeading'] = '1';
$conf['tpl']['bootstrap3']['useLocalBootswatch'] = '0';
$conf['tpl']['bootstrap3']['leftSidebarGrid'] = 'col-sm-3 col-md-3';
$conf['tpl']['bootstrap3']['showTranslation'] = '1';
$conf['tpl']['bootstrap3']['showHomePageLink'] = '1';
$conf['tpl']['bootstrap3']['showEditBtn'] = 'always';
$conf['tpl']['bootstrap3']['individualTools'] = '1';
$conf['tpl']['bootstrap3']['showAdminMenu'] = '1';
$conf['tpl']['bootstrap3']['useLegacyNavbar'] = '1';
$conf['tpl']['bootstrap3']['showAddNewPage'] = 'always';
$conf['tpl']['bootstrap3']['pageOnPanel'] = '0';
$conf['tpl']['bootstrap3']['tableFullWidth'] = '0';
$conf['tpl']['bootstrap3']['pageToolsAnimation'] = '0';
$conf['tpl']['bootstrap3']['showPageId'] = '0';
$conf['tpl']['bootstrap3']['showBadges'] = '0';
$conf['tpl']['bootstrap3']['tocAffix'] = '0';
$conf['tpl']['bootstrap3']['tocCollapseSubSections'] = '0';
$conf['tpl']['bootstrap3']['tocCollapseOnScroll'] = '0';
$conf['tpl']['bootstrap3']['googleAnalyticsNoTrackAdmin'] = '0';
$conf['tpl']['bootstrap3']['showPageInfo'] = '0';
$conf['tpl']['bootstrap3']['tagsOnTop'] = '0';
$conf['tpl']['bootstrap3']['useAnchorJS'] = '0';

// end auto-generated content
